name: 'docker'
on: 'push'

jobs:
  build:
    name: 'Docker'
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello perso'
        id: 'hello'
        uses: 'aurelien-alet/test-action-docker@v1'
        with:
          who-to-greet: 'Aurélien'
      - name: 'Output Time'
        run: 'echo "Time : ${{ steps.hello.outputs.time }}"'
        
