name: test-workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo 'Hello world 2'
      - name: Hello world reference
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet:  Aurélien
        
